### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by axredneck** [mki1967/mki3dgame#5]
```
[redneck@pylesos ~]$ flatpak run io.github.mki1967.mki3dgame
/app/bin
 Trying to use default path to assets: '/app/share/games/mki3dgame/assets'
zenity version: Gtk-Message: Failed to load module "canberra-gtk-module"
3.26.0

GLFW: An uncaught error has occurred: PlatformError: Linux: Failed to watch for joystick connections in /dev/input: No such file or directory
GLFW: Please report this bug in the Go package immediately.
2018/07/13 02:05:39 PlatformError: Linux: Failed to open joystick device directory /dev/input: No such file or directory
panic: failed to compile
#version 330
in vec3 TexCoords;
// out vec4 gl_FragColor;
uniform samplerCube skybox;
void main()
{
    gl_FragColor = textureCube(skybox, TexCoords);
}
: 0(8) : warning C7533: global variable gl_FragColor is deprecated after version 120
0(8) : error C7531: global function textureCube requires "#extension GL_NV_shadow_samplers_cube : enable" before use

goroutine 1 [running, locked to thread]:
github.com/mki1967/go-skybox/sbxgpu.(*SbxGpu).makeShaderProgram(0xc42001dfc0)
        /app/go/src/github.com/mki1967/go-skybox/sbxgpu/draw-shaders.go:84 +0x286
github.com/mki1967/go-skybox/sbxgpu.NewSbxGpu(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /app/go/src/github.com/mki1967/go-skybox/sbxgpu/sboxgpu.go:23 +0x57
main.MakeEmptyGame(0xc42001c151, 0x21, 0xc4200c4000, 0x9, 0x0, 0x0)
        /app/go/src/github.com/mki1967/mki3dgame/game.go:120 +0x2b9
main.main()
        /app/go/src/github.com/mki1967/mki3dgame/main.go:148 +0x322
[redneck@pylesos ~]$
```
Game installed form flathub.
My system: Arch Linux, Nvidia 396.24 (drivers from flathub and from Arch repo), Geforce 1050.

**Comment by mki1967** [comment]
@axredneck  Thank you for the information. 
I have added `#extension GL_NV_shadow_samplers_cube : enable` to the shader in https://github.com/mki1967/go-skybox . I have also eliminated the deprecated 
 `gl_FragColor`. 
The new version 1.14.1 should be already available on: [Flathub](https://flathub.org/apps/details/io.github.mki1967.mki3dgame).
Does this updated version  work now on your system?

**Comment by axredneck** [comment]
Thank You!
